### ISSUE TITLE
页面能正常跑，但是为什么修改jsx不会刷新页面

### ISSUE THREAD

**Issue by hechuanhua** [vikingmute/webpack-react-kit#2]
![qq 20160426142009](https://cloud.githubusercontent.com/assets/8540940/14808726/51723ac2-0bba-11e6-9b16-649c759f096a.png)
我在return里面加了个1111，页面一直没反应，修改scss或者其他文件都没反应，不知道怎么回事；
还有你的pageage.json里面貌似少了一句  new webpack.HotModuleReplacementPlugin(),不然会报错

**Comment by vikingmute** [comment]
我用最新版的 React Hot Loader代替了原来的 react hmr 各位可以更新试试

**Comment by bailicangdu** [comment]
一开始修改数据console.log提示更新了，但是页面还是没反应， devtool: 'eval-source-map'修改成devtool: 'cheap-module-eval-source-map'就可以了

**Comment by hechuanhua** [comment]
已修复
